In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("E:\Datasets\diabetes.csv")

In [3]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
data['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [5]:
data.shape

(768, 9)

In [6]:
data['SkinThickness'].unique()

array([35, 29,  0, 23, 32, 45, 19, 47, 38, 30, 41, 33, 26, 15, 36, 11, 31,
       37, 42, 25, 18, 24, 39, 27, 21, 34, 10, 60, 13, 20, 22, 28, 54, 40,
       51, 56, 14, 17, 50, 44, 12, 46, 16,  7, 52, 43, 48,  8, 49, 63, 99],
      dtype=int64)

In [7]:
data['Insulin'].unique()

array([  0,  94, 168,  88, 543, 846, 175, 230,  83,  96, 235, 146, 115,
       140, 110, 245,  54, 192, 207,  70, 240,  82,  36,  23, 300, 342,
       304, 142, 128,  38, 100,  90, 270,  71, 125, 176,  48,  64, 228,
        76, 220,  40, 152,  18, 135, 495,  37,  51,  99, 145, 225,  49,
        50,  92, 325,  63, 284, 119, 204, 155, 485,  53, 114, 105, 285,
       156,  78, 130,  55,  58, 160, 210, 318,  44, 190, 280,  87, 271,
       129, 120, 478,  56,  32, 744, 370,  45, 194, 680, 402, 258, 375,
       150,  67,  57, 116, 278, 122, 545,  75,  74, 182, 360, 215, 184,
        42, 132, 148, 180, 205,  85, 231,  29,  68,  52, 255, 171,  73,
       108,  43, 167, 249, 293,  66, 465,  89, 158,  84,  72,  59,  81,
       196, 415, 275, 165, 579, 310,  61, 474, 170, 277,  60,  14,  95,
       237, 191, 328, 250, 480, 265, 193,  79,  86, 326, 188, 106,  65,
       166, 274,  77, 126, 330, 600, 185,  25,  41, 272, 321, 144,  15,
       183,  91,  46, 440, 159, 540, 200, 335, 387,  22, 291, 39

In [8]:
data['Pregnancies'].unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14],
      dtype=int64)

In [9]:
target=data['Outcome']
feature=data.drop('Outcome',axis=1)

In [10]:
from imblearn.over_sampling import SMOTE
smot=SMOTE(random_state=0, n_jobs=8)
x,y=smot.fit_resample(feature,target)

In [11]:
from sklearn.preprocessing import StandardScaler
scl=StandardScaler()
scl.fit(x)
scl_data=scl.transform(x)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(scl_data,y,test_size=0.2)

In [13]:
import tensorflow as tf
from tensorflow.keras import Sequential,layers

In [14]:
model=Sequential()
model.add(layers.Dense(32,input_dim=(8),activation='relu'))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))

In [15]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [16]:
model.fit(x_train,y_train,epochs=10,batch_size=10)

Epoch 1/10
80/80 [==============================] - 0s 969us/step - loss: 0.6227 - accuracy: 0.6546
Epoch 2/10
80/80 [==============================] - 0s 855us/step - loss: 0.5217 - accuracy: 0.7469
Epoch 3/10
80/80 [==============================] - 0s 844us/step - loss: 0.4663 - accuracy: 0.7622
Epoch 4/10
80/80 [==============================] - 0s 853us/step - loss: 0.4575 - accuracy: 0.7851
Epoch 5/10
80/80 [==============================] - 0s 856us/step - loss: 0.4536 - accuracy: 0.7653
Epoch 6/10
80/80 [==============================] - 0s 831us/step - loss: 0.4293 - accuracy: 0.7954
Epoch 7/10
80/80 [==============================] - 0s 863us/step - loss: 0.4126 - accuracy: 0.7958
Epoch 8/10
80/80 [==============================] - 0s 736us/step - loss: 0.4365 - accuracy: 0.7898
Epoch 9/10
80/80 [==============================] - 0s 835us/step - loss: 0.4327 - accuracy: 0.7943
Epoch 10/10
80/80 [==============================] - 0s 848us/step - loss: 0.4128 - accuracy: 0.8086

In [17]:
pred=model.predict(x_test)

res=[round(x[0]) for x in pred]

In [18]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [19]:
print(classification_report(y_test,res))

              precision    recall  f1-score   support

           0       0.81      0.82      0.81       107
           1       0.79      0.77      0.78        93

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.80      0.80      0.80       200



In [20]:
accuracy_score(y_test,res)

0.8